### ISSUE TITLE
Can't run piper

### ISSUE THREAD

**Issue by Cakedy** [libratbag/piper#208]
I am getting a `KeyError: 4294967295`

**Comment by Cakedy** [comment]
Also compiled from source.

**Comment by Cakedy** [comment]
Also when getting piper from the AUR, I am getting a `TypeError: Argument 2 does not allow None as a value`

**Comment by Hjdskes** [comment]
The `KeyError` is an issue that should be fixed, if I remember correctly. Are you using the latest master versions of both libratbag and Piper?

**Comment by Cakedy** [comment]
I was

**Comment by lrenaud** [comment]
I've just pulled the latest piper and libratbag and the bug is indeed still present.

**Comment by whot** [comment]
There are a bunch of places in the DBus API where we still send -1 or ratbag errors (which are negative). It just needs to be reviewed and piper needs to be adjusted  to deal with that correctly. Coincidentally, piper should verify *any* data coming in from DBus anyway since it's technically untrusted data.

As for this specific error, @Cakedy we'll need a stacktrace please to figure out where this happens.

**Comment by Hjdskes** [comment]
> Coincidentally, piper should verify any data coming in from DBus anyway since it's technically untrusted data.

Good point. I'll leave this issue open to track this here.

**Comment by phomes** [comment]
There is a chance that this will be resolved with #229 and the similar patch in libratbag

**Comment by verstatx** [comment]
I had this happen with a g502 that had a button set as unassigned from the logitech windows software (don't know if it matters). Building with the signed enum PRs makes everything work again.

**Comment by Hjdskes** [comment]
This should be resolved now with https://github.com/libratbag/libratbag/pull/516 merged. Can anyone involved check with the latest libratbag from git?

**Comment by MyLegGuy** [comment]
@Hjdskes  The version of this program I got from the Arch repo didn't work and gave me the KeyError. Compiling piper and libratbag with their latest source on Github fixed it for me.
