### ISSUE TITLE
Logitech G502 Proteus Core Logo LED option affects Profile LEDs

### ISSUE THREAD

**Issue by ifohancroft** [libratbag/piper#346]
The LED setting for the logo, doesn't affect the actual logo LED. Instead, it affects the profile LEDs and it even takes precedence over those LEDs' setting. If you set the logo LED to off, it doesn't matter whether the profile LEDs are turned on or off in the software, they don't light up. Respectively, they do light up if the logo LED is set to static and a color is chosen, even if their own setting is turned off.

Using libratbag-ratbagd version 0.9.903-1 and piper version 0.2.902-2 on Fedora 29 installed from the repo.

**Comment by dguglielmi** [comment]
Can you try updating the SVG file on your system by using the updated SVG from https://raw.githubusercontent.com/libratbag/piper/master/data/svgs/logitech-g502.svg ? I think that it's the bug I fixed here (https://github.com/libratbag/libratbag/commit/447c69f034cf497cce4131ad4502425108f00850)

If it fixed your issue, updating to libratbag >=0.9.905 and Piper >=0.2.904 will be the best option.

**Comment by ifohancroft** [comment]
Thank you!
This SVG doesn't fix the problem though.
In fact, it seems to look exactly like the one I've already had in libratbag
