### ISSUE TITLE
Logitech G502 X missing buttons in configuration

### ISSUE THREAD

**Issue by benhavo** [libratbag/piper#866]
**Information**

- `ratbagd` version (`ratbagd --version`): 0.17
- Piper version: 0.7-1
- Distribution: Manjaro
- Device: Logitech G502 X
- Kernel version (ex. `uname -srmo`): `Linux 5.15.104-2-MANJARO x86_64 GNU/Linux`

**Describe the bug**
The Buttons panel shows configuration options for buttons 0-7, but the mouse has buttons 0-10. ratbag appears to have access to all 11 buttons (see ratbagctl info output below). In addition, the 404 rat is displayed rather than an image of the mouse, but I believe the image just doesn't exist yet for this mouse (?). 

```
singing-gundi - Logitech G502 X
             Model: usb:046d:c099:0
 Number of Buttons: 11
    Number of Leds: 0
Number of Profiles: 5
Profile 0:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi
    1: 1200dpi
    2: 1600dpi (active) (default)
    3: 2400dpi
    4: 3200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'resolution-alternate'
  Button: 5 is mapped to 'button 5'
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'resolution-up'
  Button: 10 is mapped to 'resolution-down'
Profile 1:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800dpi
    1: 1200dpi
    2: 1600dpi (active) (default)
    3: 2400dpi
    4: 3200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'button 5'
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'profile-cycle-up'
  Button: 9 is mapped to 'resolution-up'
  Button: 10 is mapped to 'resolution-down'
Profile 2: (disabled) (active)
Profile 3: (disabled)
Profile 4: (disabled)
```
**To Reproduce**
Please make sure your bug is reproducible with the CLI client, `ratbagctl`. If it is not open a bug report in libratbag instead.

1. Go to 'Buttons'
2. See only 8 buttons configurable for the mouse. The mouse has 11 configurable buttons
**Logs**
Please start the daemon with verbosity and reproduce the issue.

First make sure it isn't running already.
```
$ ratbagd --verbose=raw
Initializing libratbag
ratbag debug: New device: Logitech G502 X
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc099
ratbag debug: Logitech G502 X is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc099
ratbag debug: Logitech G502 X is device '/dev/hidraw2'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: hidpp: device supports short reports
ratbag debug: hidpp: device supports long reports
ratbag raw: hidpp write:  10 ff 00 18 00 00 00
ratbag raw: hidpp read:   11 ff 00 18 04 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 00 08 00 01 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: hidpp write:  10 ff 01 08 00 00 00
ratbag raw: hidpp read:   11 ff 01 08 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 00 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 01 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 02 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 03 00 04 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 03 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 04 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 05 00 00
ratbag raw: hidpp read:   11 ff 01 18 00 c2 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 06 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 01 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 07 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 02 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 08 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 05 60 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 09 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 06 70 08 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0a 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 75 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0b 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 a1 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0c 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 b1 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0d 00 00
ratbag raw: hidpp read:   11 ff 01 18 18 c0 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0e 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 0f 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e 22 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 10 00 00
ratbag raw: hidpp read:   11 ff 01 18 1e b0 70 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 11 00 00
ratbag raw: hidpp read:   11 ff 01 18 21 21 00 01 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 12 00 00
ratbag raw: hidpp read:   11 ff 01 18 22 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 13 00 00
ratbag raw: hidpp read:   11 ff 01 18 80 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 14 00 00
ratbag raw: hidpp read:   11 ff 01 18 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 01 18 15 00 00
ratbag raw: hidpp read:   11 ff 01 18 81 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: 'Logitech G502 X' is using protocol v4.2
ratbag raw: 'Logitech G502 X' has 22 features
ratbag raw: Init feature HIDPP_PAGE_ROOT (0x0000) 
ratbag raw: hidpp write:  10 ff 00 08 00 00 00
ratbag raw: hidpp read:   11 ff 00 08 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0000 is at 0x00
ratbag raw: Init feature HIDPP_PAGE_FEATURE_SET (0x0001) 
ratbag raw: hidpp write:  10 ff 00 08 00 01 00
ratbag raw: hidpp read:   11 ff 00 08 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0001 is at 0x01
ratbag raw: Init feature HIDPP_PAGE_DEVICE_INFO (0x0003) 
ratbag raw: hidpp write:  10 ff 00 08 00 03 00
ratbag raw: hidpp read:   11 ff 00 08 02 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0003 is at 0x02
ratbag raw: unknown feature 0x0003
ratbag raw: Init feature HIDPP_PAGE_DEVICE_NAME (0x0005) 
ratbag raw: hidpp write:  10 ff 00 08 00 05 00
ratbag raw: hidpp read:   11 ff 00 08 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0005 is at 0x03
ratbag raw: unknown feature 0x0005
ratbag raw: Init feature HIDPP_PAGE_RESET (0x0020) 
ratbag raw: hidpp write:  10 ff 00 08 00 20 00
ratbag raw: hidpp read:   11 ff 00 08 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x0020 is at 0x04
ratbag raw: unknown feature 0x0020
ratbag raw: Init feature 0xc2 (0x00c2) 
ratbag raw: hidpp write:  10 ff 00 08 00 c2 00
ratbag raw: hidpp read:   11 ff 00 08 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x00c2 is at 0x05
ratbag raw: unknown feature 0x00c2
ratbag raw: Init feature 0x1801 (0x1801) 
ratbag raw: hidpp write:  10 ff 00 08 18 01 00
ratbag raw: hidpp read:   11 ff 00 08 06 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1801 is at 0x06
ratbag raw: Init feature 0x1802 (0x1802) 
ratbag raw: hidpp write:  10 ff 00 08 18 02 00
ratbag raw: hidpp read:   11 ff 00 08 07 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1802 is at 0x07
ratbag raw: Init feature 0x1805 (0x1805) 
ratbag raw: hidpp write:  10 ff 00 08 18 05 00
ratbag raw: hidpp read:   11 ff 00 08 08 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1805 is at 0x08
ratbag raw: Init feature 0x1806 (0x1806) 
ratbag raw: hidpp write:  10 ff 00 08 18 06 00
ratbag raw: hidpp read:   11 ff 00 08 09 70 08 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1806 is at 0x09
ratbag raw: Init feature 0x1875 (0x1875) 
ratbag raw: hidpp write:  10 ff 00 08 18 75 00
ratbag raw: hidpp read:   11 ff 00 08 0a 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1875 is at 0x0a
ratbag raw: Init feature 0x18a1 (0x18a1) 
ratbag raw: hidpp write:  10 ff 00 08 18 a1 00
ratbag raw: hidpp read:   11 ff 00 08 0b 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x18a1 is at 0x0b
ratbag raw: Init feature 0x18b1 (0x18b1) 
ratbag raw: hidpp write:  10 ff 00 08 18 b1 00
ratbag raw: hidpp read:   11 ff 00 08 0c 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x18b1 is at 0x0c
ratbag raw: Init feature 0x18c0 (0x18c0) 
ratbag raw: hidpp write:  10 ff 00 08 18 c0 00
ratbag raw: hidpp read:   11 ff 00 08 0d 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x18c0 is at 0x0d
ratbag raw: Init feature 0x1e00 (0x1e00) 
ratbag raw: hidpp write:  10 ff 00 08 1e 00 00
ratbag raw: hidpp read:   11 ff 00 08 0e 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1e00 is at 0x0e
ratbag raw: Init feature 0x1e22 (0x1e22) 
ratbag raw: hidpp write:  10 ff 00 08 1e 22 00
ratbag raw: hidpp read:   11 ff 00 08 0f 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1e22 is at 0x0f
ratbag raw: Init feature 0x1eb0 (0x1eb0) 
ratbag raw: hidpp write:  10 ff 00 08 1e b0 00
ratbag raw: hidpp read:   11 ff 00 08 10 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x1eb0 is at 0x10
ratbag raw: Init feature 0x2121 (0x2121) 
ratbag raw: hidpp write:  10 ff 00 08 21 21 00
ratbag raw: hidpp read:   11 ff 00 08 11 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x2121 is at 0x11
ratbag raw: unknown feature 0x2121
ratbag raw: Init feature HIDPP_PAGE_ADJUSTABLE_DPI (0x2201) 
ratbag raw: hidpp write:  10 ff 00 08 22 01 00
ratbag raw: hidpp read:   11 ff 00 08 12 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x2201 is at 0x12
ratbag debug: device has adjustable dpi
ratbag raw: hidpp write:  10 ff 12 08 00 00 00
ratbag raw: hidpp read:   11 ff 12 08 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 12 18 00 00 00
ratbag raw: hidpp read:   11 ff 12 18 00 00 64 e0 32 64 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 12 28 00 00 00
ratbag raw: hidpp read:   11 ff 12 28 00 0c 80 06 40 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: sensor 0: current dpi: 3200 (default: 1600) min: 100 max: 25600 steps: 50
ratbag debug: device is at 3200 dpi (variable between 100 and 25600).
ratbag raw: Init feature HIDPP_PAGE_ADJUSTABLE_REPORT_RATE (0x8060) 
ratbag raw: hidpp write:  10 ff 00 08 80 60 00
ratbag raw: hidpp read:   11 ff 00 08 13 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8060 is at 0x13
ratbag debug: device has adjustable report rate
ratbag raw: hidpp write:  10 ff 13 08 00 00 00
ratbag raw: hidpp read:   11 ff 13 08 8b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 13 18 00 00 00
ratbag raw: hidpp read:   11 ff 13 18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: report rate is 1000
ratbag debug: device has 4 report rates
ratbag raw: Init feature HIDPP_PAGE_ONBOARD_PROFILES (0x8100) 
ratbag raw: hidpp write:  10 ff 00 08 81 00 00
ratbag raw: hidpp read:   11 ff 00 08 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8100 is at 0x14
ratbag debug: device has onboard profiles
ratbag raw: Init feature HIDPP_PAGE_MOUSE_BUTTON_SPY (0x8110) 
ratbag raw: hidpp write:  10 ff 00 08 81 10 00
ratbag raw: hidpp read:   11 ff 00 08 15 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature 0x8110 is at 0x15
ratbag debug: device has configurable mouse button spy
ratbag debug: initializing onboard profiles
ratbag raw: hidpp write:  10 ff 14 08 00 00 00
ratbag raw: hidpp read:   11 ff 14 08 01 04 01 05 02 0b 10 00 ff 0a 01 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 14 28 00 00 00
ratbag raw: hidpp read:   11 ff 14 28 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  10 ff 14 48 00 00 00
ratbag raw: hidpp read:   11 ff 14 48 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: current active profile is index: 1 unknown_0: 0
ratbag debug: Reading sector 0x0000
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 01 01 00 00 02 01 00 00 03 00 00 00 04 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 05 00 00 ff ff 00 00 ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 00 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff d9 6a
ratbag debug: Parsing profile 0
ratbag debug: Reading sector 0x0001
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 01 02 00 20 03 b0 04 40 06 60 09 80 0c ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 80 01 00 01 80 01 00 02 80 01 00 04 80 01 00 08
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 07 ff 00 80 01 00 10 90 01 ff 00 90 02 ff 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0a ff 00 90 03 ff 00 90 04 ff 00 ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 04 00 00 00 00 00 00 40 01 00 1f 04 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 40 01 00 1f 04 00 00 00 00 00 00 40 01 00
ratbag raw: hidpp write:  11 ff 14 58 00 01 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 1f 04 00 00 00 00 00 00 40 01 00 1f ff 35 7b
ratbag debug: Parsing profile 1
ratbag debug: Reading sector 0x0002
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 01 02 00 20 03 b0 04 40 06 60 09 80 0c ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 80 01 00 01 80 01 00 02 80 01 00 04 80 01 00 08
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0b ff 00 80 01 00 10 90 01 ff 00 90 02 ff 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0a ff 00 90 03 ff 00 90 04 ff 00 ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 04 00 00 00 00 00 00 40 01 00 1f 04 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 40 01 00 1f 04 00 00 00 00 00 00 40 01 00
ratbag raw: hidpp write:  11 ff 14 58 00 02 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 1f 04 00 00 00 00 00 00 40 01 00 1f ff aa e8
ratbag debug: Parsing profile 2
ratbag debug: Reading sector 0x0003
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 01 02 00 20 03 b0 04 40 06 60 09 80 0c ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 80 01 00 01 80 01 00 02 80 01 00 04 80 01 00 08
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 07 ff 00 80 01 00 10 90 01 ff 00 90 02 ff 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0a ff 00 90 03 ff 00 90 04 ff 00 ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 04 00 00 00 00 00 00 40 01 00 1f 04 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 40 01 00 1f 04 00 00 00 00 00 00 40 01 00
ratbag raw: hidpp write:  11 ff 14 58 00 03 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 1f 04 00 00 00 00 00 00 40 01 00 1f ff 35 7b
ratbag debug: Parsing profile 3
ratbag debug: Reading sector 0x0004
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 01 02 00 20 03 b0 04 40 06 60 09 80 0c ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 80 01 00 01 80 01 00 02 80 01 00 04 80 01 00 08
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 07 00 00 80 01 00 10 90 01 00 00 90 02 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0a 00 00 90 03 00 00 90 04 00 00 ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 04 00 00 00 00 00 00 40 01 00 1f 04 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 40 01 00 1f 00 ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 04 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff 05 6a
ratbag debug: Parsing profile 4
ratbag debug: Reading sector 0x0005
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 01 02 00 20 03 b0 04 40 06 60 09 80 0c ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 10 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 20 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 80 01 00 01 80 01 00 02 80 01 00 04 80 01 00 08
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 30 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 07 00 00 80 01 00 10 90 01 00 00 90 02 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 40 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 90 0a 00 00 90 03 00 00 90 04 00 00 ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 50 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 60 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 70 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 80 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 90 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 a0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 b0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 c0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 d0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 04 00 00 00 00 00 00 40 01 00 1f 04 00 00 00 00
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 e0 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 00 00 40 01 00 1f 00 ff ff ff ff ff ff ff ff ff
ratbag raw: hidpp write:  11 ff 14 58 00 05 00 ef 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: hidpp read:   11 ff 14 58 ff ff ff ff ff ff ff ff ff ff ff ff ff ff 05 6a
ratbag raw: hidpp write:  10 ff 14 b8 00 00 00
ratbag raw: hidpp read:   11 ff 14 b8 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag debug: driver match found: Logitech HID++2.0
hidraw1: "Logitech G502 X", 5 profiles
ratbag debug: New device: Logitech G502 X
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver hidpp20
ratbag debug: hidraw info: bus 0x03 vendor 0x46d product 0xffffc099
ratbag debug: Logitech G502 X is device '/dev/hidraw1'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: Keychron Keychron K8 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0280
ratbag debug: New device: Keychron Keychron K8 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0280
ratbag debug: New device: Keychron Keychron K8 Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0280
ratbag debug: New device: MSI MYSTIC LIGHT 
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1462:7c37
DBus server ready
```

**Additional context**

**Comment by staticssleever668** [comment]
Fixed by #794 (not in a release yet).

**Comment by Danie10** [comment]
This is pretty sad as there has been a potential fix for over a year, but no release. Which means for end users it is actually not resolved. I'm a brand-new user (got this mouse today) so this is a bit disappointing.
